### ISSUE TITLE
NBT API doesn't work

### ISSUE THREAD

**Issue by RalphORama** [podaboutlist/minecraft#1]
[NBT API](https://www.spigotmc.org/resources/nbt-api.7939/) version `2.9.0-SNAPSHOT` seems to be broken and causes errors for the following plugins:

- Vouchers
- CrazyCrates

Check if this issue persists when plugins update.

**Comment by RalphORama** [comment]
Error from CrazyCrates:

```log
[01:14:50 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_18_R1! Trying to find NMS support
[01:14:50 WARN]: [NBTAPI] [NBTAPI] Wasn't able to find NMS Support! Some functions may not work!
[01:14:50 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setFloat' in 'NBTTagCompound' Enum: COMPOUND_SET_FLOAT
[01:14:50 WARN]: Nag author(s): '[BadBones69]' of 'CrazyCrates' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setString' in 'NBTTagCompound' Enum: COMPOUND_SET_STRING
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setInt' in 'NBTTagCompound' Enum: COMPOUND_SET_INT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setByteArray' in 'NBTTagCompound' Enum: COMPOUND_SET_BYTEARRAY
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setIntArray' in 'NBTTagCompound' Enum: COMPOUND_SET_INTARRAY
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setLong' in 'NBTTagCompound' Enum: COMPOUND_SET_LONG
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setShort' in 'NBTTagCompound' Enum: COMPOUND_SET_SHORT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setByte' in 'NBTTagCompound' Enum: COMPOUND_SET_BYTE
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setDouble' in 'NBTTagCompound' Enum: COMPOUND_SET_DOUBLE
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setBoolean' in 'NBTTagCompound' Enum: COMPOUND_SET_BOOLEAN
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'set' in 'NBTTagCompound' Enum: COMPOUND_SET
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'get' in 'NBTTagCompound' Enum: COMPOUND_GET
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getList' in 'NBTTagCompound' Enum: COMPOUND_GET_LIST
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getFloat' in 'NBTTagCompound' Enum: COMPOUND_GET_FLOAT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getString' in 'NBTTagCompound' Enum: COMPOUND_GET_STRING
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getInt' in 'NBTTagCompound' Enum: COMPOUND_GET_INT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getByteArray' in 'NBTTagCompound' Enum: COMPOUND_GET_BYTEARRAY
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getIntArray' in 'NBTTagCompound' Enum: COMPOUND_GET_INTARRAY
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getLong' in 'NBTTagCompound' Enum: COMPOUND_GET_LONG
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getShort' in 'NBTTagCompound' Enum: COMPOUND_GET_SHORT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getByte' in 'NBTTagCompound' Enum: COMPOUND_GET_BYTE
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getDouble' in 'NBTTagCompound' Enum: COMPOUND_GET_DOUBLE
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getBoolean' in 'NBTTagCompound' Enum: COMPOUND_GET_BOOLEAN
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getCompound' in 'NBTTagCompound' Enum: COMPOUND_GET_COMPOUND
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getTag' in 'ItemStack' Enum: NMSITEM_GETTAG
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'save' in 'ItemStack' Enum: NMSITEM_SAVE
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'remove' in 'NBTTagCompound' Enum: COMPOUND_REMOVE_KEY
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'hasKey' in 'NBTTagCompound' Enum: COMPOUND_HAS_KEY
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getKeys' in 'NBTTagCompound' Enum: COMPOUND_GET_KEYS
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getKeys' in 'NBTTagCompound' Enum: LISTCOMPOUND_GET_KEYS
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'set' in 'NBTTagList' Enum: LIST_SET
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'add' in 'NBTTagList' Enum: LIST_ADD
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getString' in 'NBTTagList' Enum: LIST_GET_STRING
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'setTag' in 'ItemStack' Enum: ITEMSTACK_SET_TAG
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getTileEntity' in 'WorldServer' Enum: NMS_WORLD_GET_TILEENTITY
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'removeTileEntity' in 'WorldServer' Enum: NMS_WORLD_REMOVE_TILEENTITY
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'save' in 'TileEntity' Enum: TILEENTITY_GET_NBT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'load' in 'TileEntity' Enum: TILEENTITY_SET_NBT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getBlock' in 'TileEntity' Enum: TILEENTITY_GET_BLOCKDATA
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'load' in 'Entity' Enum: NMS_ENTITY_SET_NBT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'save' in 'Entity' Enum: NMS_ENTITY_GET_NBT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getSaveID' in 'Entity' Enum: NMS_ENTITY_GETSAVEID
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'parse' in 'MojangsonParser' Enum: PARSE_NBT
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'keySet' in 'RegistryMaterials' Enum: REGISTRYMATERIALS_KEYSET
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'get' in 'RegistryMaterials' Enum: REGISTRYMATERIALS_GET
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'getKey' in 'RegistryMaterials' Enum: REGISTRYMATERIALS_GETKEY
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'deserialize' in 'GameProfileSerializer' Enum: GAMEPROFILE_DESERIALIZE
[01:14:50 INFO]: [CrazyCrates] [STDOUT] [NBTAPI] Unable to find the method 'serialize' in 'GameProfileSerializer' Enum: GAMEPROFILE_SERIALIZE
[01:14:50 WARN]: [CrazyCrates] There was an error while loading the Basic.yml file.
[01:14:50 WARN]: me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NbtApiException: Exception while getting an Itemstack's NBTCompound!
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:125)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTItem.getCompound(NBTItem.java:53)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:608)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTCompound.hasKey(NBTCompound.java:514)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.api.objects.ItemBuilder.convertItemStack(ItemBuilder.java:163)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.api.objects.Crate.<init>(Crate.java:62)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.api.CrazyCrates.loadCrates(CrazyCrates.java:283)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.Main.onEnable(Main.java:78)
[01:14:50 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:14:50 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:14:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[01:14:50 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[01:14:50 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[01:14:50 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:14:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:14:50 WARN]: Caused by: me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NbtApiException: Method not loaded! 'NMSITEM_GETTAG'
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:160)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:122)
[01:14:50 WARN]:        ... 18 more
[01:14:50 WARN]: [CrazyCrates] There was an error while loading the Crazy.yml file.
[01:14:50 WARN]: me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NbtApiException: Exception while getting an Itemstack's NBTCompound!
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:125)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTItem.getCompound(NBTItem.java:53)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:608)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTCompound.hasKey(NBTCompound.java:514)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.api.objects.ItemBuilder.convertItemStack(ItemBuilder.java:163)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.api.objects.Crate.<init>(Crate.java:62)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.api.CrazyCrates.loadCrates(CrazyCrates.java:283)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.Main.onEnable(Main.java:78)
[01:14:50 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:14:50 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:14:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[01:14:50 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[01:14:50 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[01:14:50 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:14:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:14:50 WARN]: Caused by: me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NbtApiException: Method not loaded! 'NMSITEM_GETTAG'
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:160)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:122)
[01:14:50 WARN]:        ... 18 more
[01:14:50 WARN]: [CrazyCrates] There was an error while loading the Classic.yml file.
[01:14:50 WARN]: me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NbtApiException: Exception while getting an Itemstack's NBTCompound!
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:125)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTItem.getCompound(NBTItem.java:53)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:608)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTCompound.hasKey(NBTCompound.java:514)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.api.objects.ItemBuilder.convertItemStack(ItemBuilder.java:163)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.api.objects.Crate.<init>(Crate.java:62)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.api.CrazyCrates.loadCrates(CrazyCrates.java:283)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.Main.onEnable(Main.java:78)
[01:14:50 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:14:50 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:14:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[01:14:50 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[01:14:50 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[01:14:50 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[01:14:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:14:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:14:50 WARN]: Caused by: me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NbtApiException: Method not loaded! 'NMSITEM_GETTAG'
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:160)
[01:14:50 WARN]:        at CrazyCrates-1.10.2.jar//me.badbones69.crazycrates.nbtapi.changeme.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:122)
[01:14:50 WARN]:        ... 18 more
```

**Comment by RalphORama** [comment]
I don't know how I just fixed this but I did 🙂
